---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install Applications
      package:
        name:
          - htop
          - tmux
          - vim
          - curl
          - nmap
          - cmatrix
          - calibre
          - vlc
          - gimp

    - name: Copy Wallpaper file
      copy:
        src: files/DebianWallPaper.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg
        owner: root
        group: root

    - name: Set Wallpaper
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"
    - name: Set wallpaper position
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
    - name: Run a script with arguments (free form)
        ansible.builtin.script: "/home/phranc/code/ansible/Linux_Desktop/files/frank.sh"
