---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: install htop
      package:
        name:
          - htop
          - tmux
          - vim
          - curl
          - nmap
          - cmatrix
          - calibre
          - vlc
          - gimp

